# Example Data
pos1 = posx(300,0,0,0,180,0) # Teaching pose1
pos2 = posx(800,0,0,0,180,0) # Teaching pose2
pos3 = posx(0,500,0,0,180,0) # Teaching pose3
pos4 = posx(800,500,0,0,180,0) # Teaching pose4
direction = 0 # Normal Pallet -> 0: Snake, 1: Zigzag / Rhombus Pallet -> 2: Snake, 3: Zigzag
row = 3
column = 3
stack = 1
thickness = 0
point_offset = [0, 0, 0] # Offset for calculated pose
 
# Total count
if direction < 2: # Normal Pallet
    total_count = row * column * stack
else: # Rhombus Pallet
    total_count = (row * column - int(row/2)) * stack
 
# Calculate Pallet Pose (Resulted in base coordinate)
for pallet_index in range(0, total_count):
    Pallet_Pose = get_pattern_point(pos1, pos2, pos3, pos4, pallet_index, direction, row, column, stack, thickness, point_offset)
    tp_popup("cnt={}".format( pallet_index))
    tp_popup("point={}".format(Pallet_Pose))
  